### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by agrippa1994** [mschnitzer/mutex-test#1]
Warum verwendest du nicht gleich den C++ mutex? :smile:

**Comment by mschnitzer** [comment]
Ich habe mir was durchgelesen diesbezüglich und die haben nur den pthread Mutex verwendet. Ist der andere besser?

**Comment by agrippa1994** [comment]
std::thread und std::lock_guard. Gründe dafür sind die Standardisierung, sprich, sie funktionieren auf jeden System

**Comment by mschnitzer** [comment]
Ja, habe ich mittlerweile bereits gelesen ;-) Danke Dir.
